### ISSUE TITLE
Slow import due to pkg_resources

### ISSUE THREAD

**Issue by Ristovski** [securisec/ripgrepy#12]
Importing `pkg_resources` is slow (see https://github.com/pypa/setuptools/issues/926 et al).

As a demonstration, dropping the following `import pkg_resources` and hardcoding the version improves the import times significantly, from ~400ms down to ~20ms.
https://github.com/securisec/ripgrepy/blob/3fc9092d1b41516519a802ef477060fb2b3613af/ripgrepy/__init__.py#L8-L11

Baseline, `argparse` as example:

```
$ python3 -c 'import timeit; t = timeit.Timer("import argparse").timeit(number=10); print(f"{t:.3f} seconds")'
0.010 seconds
```

ripgrepy, `pkg_resources` version:

```
$ python3 -c 'import timeit; t = timeit.Timer("import ripgrepy").timeit(number=10); print(f"{t:.3f} seconds")'
0.397 seconds
```

ripgrepy, hardcoded version:

```
$ python3 -c 'import timeit; t = timeit.Timer("import ripgrepy").timeit(number=10); print(f"{t:.3f} seconds")'
0.019 seconds
```

**Comment by securisec** [comment]
Thank you for the great suggestion! It has been addressed for the next major release.
