### ISSUE TITLE
JSONDecodeError thrown if file does not exist

### ISSUE THREAD

**Issue by krisfremen** [securisec/ripgrepy#17]
**Describe the bug**

`json.decoder.JSONDecodeError` is thrown when using `as_dict` or `as_json` with a file that does not exist.

**To Reproduce**
```
from ripgrepy import Ripgrepy
Ripgrepy("test", "nonexistent.file").json().run().as_dict
```

**Expected behavior**
Would be nice if the dict/json would be populated with an error or raises a specific exception that can be caught instead of a generic JSONDecodeError.

**Desktop (please complete the following information):**
 - OS: Linux
 - Python Version 3.12

**Additional context**
`rg: nonexistent: No such file or directory (os error 2)` is the output when using `as_string`

**Comment by securisec** [comment]
As under the hood ripgrepy is running system ripgrep using subprocess, it seems cumbersome on my end to do a stat for a file or directory and update the json parser (it relies on json output from ripgrep). It might be easier for user code to do a stat using `pathlib` before ripgrepy is run.
