### ISSUE TITLE
Feature Request: Add pyi type stubs for type checking support

### ISSUE THREAD

**Issue by DeflateAwning** [securisec/ripgrepy#30]

**Comment by DeflateAwning** [comment]
Wow that's awesome, thanks! Would you consider doing a release to include these changes?

**Comment by securisec** [comment]
@DeflateAwning I released 2.0.1 https://pypi.org/project/ripgrepy/2.0.1/. If that doesnt work, feel free to make a PR!

**Comment by DeflateAwning** [comment]
Wow nice, thanks! Looks decent overall. It'd be nice to add more static type hinting in general, but this is a good start.

Thoughts on adding more static type hinting?

**Comment by securisec** [comment]
I am not sure what you mean by more static type hinting. But feel free to make a PR!

**Comment by DeflateAwning** [comment]
I may!

What I mean is that, if you enable `pyright` in strict mode on this repo, it points out lots of issues.

For example, the `as_dict` property/method's return type is a `list`. However, in strict typing, it is a `list[dict[str, Any]]`. Or furthermore, a `TypedDict` could be used to help define the fields expected within that dict (e.g., `path`, etc.). 

These sorts of type hints make using this library in other projects easier, safer, and more reliable.
