### ISSUE TITLE
.iglob method does not support paths containing forward slash

### ISSUE THREAD

**Issue by Lng88** [securisec/ripgrepy#4]
Hey there, first off thanks for building this great tool. 

I'm trying to ignore some files and paths using the `.iglob` method. However when I try to ignore a path like `build/index.js`, these lines are completely ignored. It seems like the only thing that works is if I have just the name of the directory or file by itself and any paths after the forward slash is ignored.

test/build/index.js - completely ignored
test - will ignore everything under `test` dir
build - will ignore everything under `build` dir

Here's a codesnippet of what my implementation looks like
```python
rg_options = rg(biased_word, path).ignore_case().hidden()
        for item in excluded:
            rg_options = rg_options.iglob('!%s' % item)
```

**Comment by securisec** [comment]
@Lng88 can you include the working ripgrep command itself? 

Also, underlying, the lib simply executes a shell command. So I would recommend escaping `!` just like you would in the cli.

**Comment by securisec** [comment]
Cannot replicate. 

```py
from ripgrepy import Ripgrepy
import re

r = Ripgrepy('imp.+re$', 'dev/scrap/py'
).run()

print(r)
```

```
dev/scrap/py/2.py:import re
dev/scrap/py/test/lol/1.py:import re
```

```py
from ripgrepy import Ripgrepy
import re

r = Ripgrepy('imp.+re$', 'dev/scrap/py'
).iglob('!test/lol').run()

print(r)
```

```
dev/scrap/py/2.py:import re
```

**Comment by Lng88** [comment]
Thanks for getting back so quickly. I wasn't able to replicate this with the CLI ripgrep command either, however I replicated your test and for some reason, both runs with and without the `.iglob` method still display the below:
```
dev/scrap/py/test/lol/1.py:import re
dev/scrap/py/2.py:import re
```

When I remove the `/lol` path to just `('!test')`, the ignore works.

**Comment by securisec** [comment]
Are you on windows by any chance? I have not tested this on windows, but seems to be working fine on OSX. Should be fine in Linux also.

**Comment by Lng88** [comment]
I'm on macOS 10.15

**Comment by sarahotis** [comment]
Hi @securisec, I'm having the same issue. I see the output that @Lng88 sees, as does a coworker of mine.

```
from ripgrepy import Ripgrepy
import re
r = Ripgrepy('imp.+re$', 'dev/scrap/py').run()
print("Option one:")
print(r)
r = Ripgrepy('imp.+re$', 'dev/scrap/py').iglob('!test/lol').run()
print("Option two:")
print(r)
```
<img width="358" alt="Screen Shot 2020-12-11 at 11 17 21 AM" src="https://user-images.githubusercontent.com/28989931/101945166-a5f57600-3ba2-11eb-893e-2bf3ed5d61a9.png">

Is it possible to investigate further? Thanks

**Comment by securisec** [comment]
@sarahotis please include a working example of how the ripgrep command line tool behaves in this case, and what it is supposed to display. As mentioned before, i was not able to replicate the behavior. With working examples of `rg` cli, it will help narrow down whether this is a ripgrepy issue, or user issue.  

As mentioned before, I cannot replicate this. 

```
❯❯ rg 'imp.+re$'
2.py
1:import re

test/lol/1.py
1:import re
dev/scrap/py
❯❯ rg --iglob '!test/lol' 'imp.+re$'
2.py
1:import re
dev/scrap/py
❯❯ python 2.py
Option one:
./2.py:import re
./test/lol/1.py:import re
Option two:
./2.py:import re
dev/scrap/py
❯❯ cat 2.py
import re

from ripgrepy import Ripgrepy

r = Ripgrepy('imp.+re$', '.').run()
print("Option one:")
print(r)
r = Ripgrepy('imp.+re$', '.').iglob('!test/lol').run()
print("Option two:")
print(r)
dev/scrap/py
❯❯
```
