### ISSUE TITLE
PyPi package not up to date

### ISSUE THREAD

**Issue by TrevorBagels** [securisec/ripgrepy#6]
I tried using `Ripgrepy.max_count`, and got an error when running because the PyPi package version only appends `"--max-count"` to the command. In the github repository, it appends `f"max-count {num}"` to the command, which, of course, works.  So it seems like the package in PyPi needs to be updated, that's all.

**Comment by securisec** [comment]
I can look into this. Can you please provide some dummy/demo datasets and the commands you are running from the command line and the expected result @TrevorBagels ?

**Comment by securisec** [comment]
Fixed with tag 1.0.3
